FROM nginx:alpine

# Copy the built output generated by the GitHub Action workflow
COPY dist /usr/share/nginx/html

# Replace default NGINX config to listen on port 1999
# Also enables SPA routing by configuring try_files to fallback to index.html
RUN echo "server { \
    listen 1999; \
    location / { \
        root /usr/share/nginx/html; \
        index index.html index.htm; \
        try_files \$uri \$uri/ /index.html; \
    } \
}" > /etc/nginx/conf.d/default.conf

EXPOSE 1999
CMD ["nginx", "-g", "daemon off;"]
